######################################################################
# Automatically generated by qmake (3.1) Thu Feb 9 09:43:30 2023
######################################################################

TEMPLATE = app
TARGET = testfold
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp

RESOURCES += resources.qrc

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target